version: "3.8"

services:
  node:
    image: "node:current"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=8080
    volumes:
      - ./:/home/node/app:consistent
    ports:
      - 8080:8080
    command: "npm run server"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
